/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIQytetet;

/**
 *
 * @author pepe
 */
public class VistaCartaSorpresa extends javax.swing.JPanel {

    /**
     * Creates new form VistaCartaSorpresa
     */
    public VistaCartaSorpresa() {
        initComponents();
    }

    public void actualizarCartaSorpresa(String descripcion){
        this.jtCartaSorpresa.setText(descripcion);
        this.repaint();
        this.revalidate();
                
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtCartaSorpresa = new javax.swing.JTextArea();

        jtCartaSorpresa.setEditable(false);
        jtCartaSorpresa.setColumns(20);
        jtCartaSorpresa.setRows(5);
        jScrollPane1.setViewportView(jtCartaSorpresa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtCartaSorpresa;
    // End of variables declaration//GEN-END:variables
}
